export const videos = {
  intro: {
    url: "intro.mp4",
    width: 1920,
    height: 1920,
    poster: "logoart.png",
  },
  brandbook: {
    url: "brandbook.mp4",
    width: 1920,
    height: 1080,
  },
  reveal: {
    url: "reveal.mp4",
    width: 1920,
    height: 1080,
    alt: "Logo reveal",
  },
  generic: {
    url: "generic-outro-portfolio.mp4",
    width: 1920,
    height: 1080,
  },
  outro: {
    url: "creative-outro.mp4",
    width: 1920,
    height: 1080,
  },
  swirl: {
    url: "swirl.mp4",
    width: 1500,
    height: 1500,
  },
};

export const images = {
  capchaseWeb0: {
    name: "capchase-web-0.png",
    width: 1200,
    height: 720,
    alt: "Analytics",
  },
  capchaseWeb1: {
    name: "capchase-web-1.png",
    width: 1200,
    height: 720,
    alt: "Mobile + Careers",
  },
  capchaseWeb2: {
    name: "capchase-web-2.png",
    width: 1200,
    height: 720,
    alt: "Landing pages",
  },
  capchaseWeb3: {
    name: "capchase-web-3.png",
    width: 1200,
    height: 720,
    alt: "Grow page",
  },
  capchaseLogo0: {
    name: "capchase-logo-0.png",
    width: 1200,
    height: 720,
    alt: "Graphical variation",
  },
  capchaseLogo1: {
    name: "capchase-logo-1.png",
    width: 1200,
    height: 720,
    alt: "Logo",
  },
  capchaseLogo2: {
    name: "capchase-logo-2.png",
    width: 1200,
    height: 720,
    alt: "Logo extensions",
  },

  capchaseBB0: {
    name: "capchase-bb-0.png",
    width: 1200,
    height: 648,
    alt: "Illustrations",
  },
  capchaseBB1: {
    name: "capchase-bb-1.png",
    width: 1200,
    height: 648,
    alt: "Index",
  },
  capchaseBB2: {
    name: "capchase-bb-2.png",
    width: 1200,
    height: 648,
    alt: "Attributes",
  },
  capchaseBB3: {
    name: "capchase-bb-3.png",
    width: 1200,
    height: 648,
    alt: "Tone of Voice",
  },
  capchaseBB4: {
    name: "capchase-bb-4.png",
    width: 1200,
    height: 648,
    alt: "Logotype",
  },
  capchaseBB5: {
    name: "capchase-bb-5.png",
    width: 1200,
    height: 648,
    alt: "Colors",
  },
  capchaseBB6: {
    name: "capchase-bb-6.png",
    width: 1200,
    height: 648,
    alt: "Billboard",
  },
  capchaseBB7: {
    name: "capchase-bb-7.png",
    width: 1200,
    height: 648,
    alt: "Background example",
  },
  capchaseBB8: {
    name: "capchase-bb-8.png",
    width: 1200,
    height: 648,
    alt: "Background example",
  },
  bottle: {
    name: "hero-bottle.png",
    width: 147,
    height: 370,
    alt: "bottle",
  },
  flow: {
    name: "hero-flow.png",
    width: 288,
    height: 281,
    alt: "Flow",
  },
  tablet: {
    name: "hero-tablet.png",
    width: 586,
    height: 544,
    alt: "Tablet",
  },
  switch: {
    name: "hero-switch.png",
    width: 368,
    height: 229,
    alt: "Switch",
  },
  heroEmbed: {
    name: "hero-embed.png",
    width: 432,
    height: 229,
    alt: "Hero embed",
  },
  heroUI: {
    name: "hero-ui.png",
    width: 576,
    height: 329,
    alt: "Hero UI",
  },
  heroLogo: {
    name: "hero-logo.png",
    width: 568,
    height: 277,
    alt: "Hero logo",
  },
  heroWatch: {
    name: "hero-watch.png",
    width: 192,
    height: 222,
    alt: "Hero watch",
  },
  heroTypo: {
    name: "hero-typo.png",
    width: 336,
    height: 269,
    alt: "Hero typo",
  },
  heroCapchase: {
    name: "hero-capchase.svg",
    width: 1200,
    height: 1214,
    alt: "Hero capchase",
  },
  heroIcon1: {
    name: "hero-icon1.png",
    width: 164,
    height: 164,
    alt: "Hero icon 1",
  },
  heroIcon2: {
    name: "hero-icon2.png",
    width: 164,
    height: 164,
    alt: "Hero icon 2",
  },
  heroIcon3: {
    name: "hero-icon3.png",
    width: 164,
    height: 164,
    alt: "Hero icon 3",
  },
  heroIcon4: {
    name: "hero-icon4.png",
    width: 164,
    height: 164,
    alt: "Hero icon 4",
  },
  heroIcon5: {
    name: "hero-icon5.png",
    width: 164,
    height: 164,
    alt: "Hero icon 5",
  },
};
