export const videos = {
  loupeMesh: {
    url: require("./assets/loupeMesh.mp4"),
    width: 1080,
    height: 1080,
  },
  mesh: {
    url: require("./assets/mesh.mp4"),
    width: 1080,
    height: 1080,
  },
  mesh1: {
    url: require("./assets/mesh1.mp4"),
    width: 1152,
    height: 1152,
  },
  muziekclip: {
    fit: "cover",
    url: require("./assets/muziekclip.mp4"),
    width: 2646,
    height: 1080,
  },
  icons: {
    url: require("./assets/icons.mp4"),
    width: 1080,
    height: 1080,
    fit: "cover",
  },
  overview: {
    url: require("./assets/overview.mp4"),
    width: 1168,
    height: 620,
  },
};

export const images = {
  shapesFilled: {
    url: require("./assets/shapesFilled.png"),
    webP: require("./assets/shapesFilled.webp"),
    width: 2340,
    height: 1818,
    alt: "logowithmesh",
  },
  logowithmesh: {
    url: require("./assets/logowithmesh.png"),
    webP: require("./assets/logowithmesh.webp"),
    width: 2340,
    height: 1200,
    alt: "logowithmesh",
  },
  meshwithnotes: {
    url: require("./assets/meshwithnotes.png"),
    webP: require("./assets/meshwithnotes.webp"),
    width: 2340,
    height: 1200,
    alt: "meshwithnotes",
  },
  overview: {
    url: require("./assets/overview.jpg"),
    webP: require("./assets/overview.webp"),
    width: 4000,
    height: 2928,
    alt: "overview",
  },
  notes: {
    url: require("./assets/notes.png"),
    webP: require("./assets/notes.webp"),
    width: 2340,
    height: 1600,
    alt: "notes",
  },
  cyan: {
    url: require("./assets/cyan.png"),
    webP: require("./assets/cyan.webp"),
    width: 2336,
    height: 1600,
    alt: "cyan",
  },
  orbs: {
    url: require("./assets/orbs.png"),
    webP: require("./assets/orbs.webp"),
    width: 2340,
    height: 1200,
    alt: "orbs",
  },
  multiMesh1: {
    url: require("./assets/multiMesh1.png"),
    webP: require("./assets/multiMesh1.webp"),
    width: 1174,
    height: 1182,
    alt: "multiMesh1",
  },
  multiMesh0: {
    url: require("./assets/multiMesh0.png"),
    webP: require("./assets/multiMesh0.webp"),
    width: 582,
    height: 582,
    alt: "multiMesh0",
  },
  logoStrip: {
    url: require("./assets/logoStrip.svg"),
    width: 102,
    height: 588,
    alt: "logoStrip",
  },
  twentytwenty: {
    url: require("./assets/2020.svg"),
    width: 81,

    height: 23,
    alt: "twentytwenty",
  },
  styrenebold: {
    url: require("./assets/styrenebold.svg"),
    width: 311,
    height: 123,
    alt: "styrenebold",
  },
  raisonne: {
    url: require("./assets/raisonne.svg"),
    width: 204,
    height: 128,
    alt: "raisonne",
  },
  styrene: {
    url: require("./assets/styrene.svg"),
    width: 217,
    height: 94,
    alt: "styrene",
  },
  monomeshMagenta1: {
    url: require("./assets/monomeshMagenta1.png"),
    webP: require("./assets/monomeshMagenta1.webp"),
    width: 1280,
    height: 1280,
    alt: "monomeshMagenta1",
  },
  monomeshMagenta: {
    url: require("./assets/monomeshMagenta.png"),
    webP: require("./assets/monomeshMagenta.webp"),
    width: 1280,
    height: 1280,
    alt: "monomeshMagenta",
  },
  monomeshRed2: {
    url: require("./assets/monomeshRed2.png"),
    webP: require("./assets/monomeshRed2.webp"),
    width: 1280,
    height: 1280,
    alt: "monomeshRed2",
  },
  monomeshOrange: {
    url: require("./assets/monomeshOrange.png"),
    webP: require("./assets/monomeshOrange.webp"),
    width: 1280,
    height: 1280,
    alt: "monomeshOrange",
  },
  monomeshRed: {
    url: require("./assets/monomeshRed.png"),
    webP: require("./assets/monomeshRed.webp"),
    width: 1280,
    height: 1280,
    alt: "monomeshRed",
  },
  monomeshCyan1: {
    url: require("./assets/monomeshCyan1.png"),
    webP: require("./assets/monomeshCyan1.webp"),
    width: 1280,
    height: 1280,
    alt: "monomeshcyan1",
  },
  pageHomeMobile: {
    url: require("./assets/pageHomeMobile.jpg"),
    webP: require("./assets/pageHomeMobile.webp"),
    width: 750,
    height: 2666,
    alt: "pageHomeMobile",
  },
  pageTickets: {
    url: require("./assets/pageTickets.jpg"),
    webP: require("./assets/pageTickets.webp"),
    width: 2336,
    height: 3204,
    alt: "pageTickets",
  },
  pageTicketsMobile: {
    url: require("./assets/pageTicketsMobile.jpg"),
    webP: require("./assets/pageTicketsMobile.webp"),
    width: 750,
    height: 4097,
    alt: "pageTicketsMobile",
  },
  pageInformation1: {
    url: require("./assets/pageInformation1.jpg"),
    webP: require("./assets/pageInformation1.webp"),
    width: 2336,
    height: 2860,
    alt: "pageInformation1",
  },
  pageInformation2: {
    url: require("./assets/pageInformation2.jpg"),
    webP: require("./assets/pageInformation2.webp"),
    width: 2336,
    height: 2558,
    alt: "pageInformation2",
  },
  pageInformation3: {
    url: require("./assets/pageInformation3.jpg"),
    webP: require("./assets/pageInformation3.webp"),
    width: 2336,
    height: 1936,
    alt: "pageInformation3",
  },
  pageWorkshops1: {
    url: require("./assets/pageWorkshops1.jpg"),
    webP: require("./assets/pageWorkshops1.webp"),
    width: 2336,
    height: 2559,
    alt: "pageWorkshops1",
  },
  pageWorkshops2: {
    url: require("./assets/pageWorkshops2.jpg"),
    webP: require("./assets/pageWorkshops2.webp"),
    width: 2336,
    height: 2608,
    alt: "pageWorkshops2",
  },
  pageSpeakers: {
    url: require("./assets/pageSpeakers.jpg"),
    webP: require("./assets/pageSpeakers.webp"),
    width: 2336,
    height: 2591,
    alt: "pageSpeakers",
  },
  pageFaq: {
    url: require("./assets/pageFaq.jpg"),
    webP: require("./assets/pageFaq.webp"),
    width: 2336,
    height: 2339,
    alt: "pageFaq",
  },
  pageHome: {
    url: require("./assets/pageHome.jpg"),
    webP: require("./assets/pageHome.webp"),
    width: 2336,
    height: 2416,
    alt: "pageHome",
  },
};
