export const colors = {
  red: "#f60000",
  cyan: "#3edbff",
  orange: "#f47722",
  green: "#003807",
  beige: "#fcf6f5",
  magenta: "#e900a1",
  maroon: "#560000",
  white: "#fff",
};

export const videos = {
  loupeMesh: {
    url: "./assets/loupeMesh.mp4",
    width: 1080,
    height: 1080,
  },
  mesh: {
    url: "./assets/mesh.mp4",
    width: 1080,
    height: 1080,
  },
  mesh1: {
    url: "./assets/mesh1.mp4",
    width: 1152,
    height: 1152,
  },
  muziekclip: {
    fit: "cover",
    url: "./assets/muziekclip.mp4",
    width: 2646,
    height: 1080,
  },
  icons: {
    url: "./assets/icons.mp4",
    width: 1080,
    height: 1080,
    fit: "cover",
  },
  overview: {
    url: "./assets/overview.mp4",
    width: 1168,
    height: 620,
  },
};

export const images = {
  logopart1: {
    url: "./assets/logopart1.png",
    width: 1,
    height: 1,
    alt: "logopart1",
  },
  logopart2: {
    url: "./assets/logopart2.png",
    width: 1,
    height: 1,
    alt: "logopart2",
  },
  logopart3: {
    url: "./assets/logopart3.png",
    width: 1,
    height: 1,
    alt: "logopart3",
  },
  logopart4: {
    url: "./assets/logopart4.png",
    width: 1,
    height: 1,
    alt: "logopart4",
  },
  logoassemble1: {
    url: "./assets/logoassemble1.png",
    width: 1,
    height: 1,
    alt: "logoassemble1",
  },
  logoassemble2: {
    url: "./assets/logoassemble2.png",
    width: 1,
    height: 1,
    alt: "logoassemble2",
  },
  logoassemble3: {
    url: "./assets/logoassemble3.png",
    width: 1,
    height: 1,
    alt: "logoassemble3",
  },
  shapesFilled: {
    url: "./assets/shapesFilled.png",
    webP: "./assets/shapesFilled.webp",
    width: 2340,
    height: 1818,
    alt: "logowithmesh",
  },
  logowithmesh: {
    url: "./assets/logowithmesh.png",
    webP: "./assets/logowithmesh.webp",
    width: 2340,
    height: 1200,
    alt: "logowithmesh",
  },
  meshwithnotes: {
    url: "./assets/meshwithnotes.png",
    webP: "./assets/meshwithnotes.webp",
    width: 2340,
    height: 1200,
    alt: "meshwithnotes",
  },
  overview: {
    url: "./assets/overview.jpg",
    webP: "./assets/overview.webp",
    width: 4000,
    height: 2928,
    alt: "overview",
  },
  notes: {
    url: "./assets/notes.png",
    webP: "./assets/notes.webp",
    width: 2340,
    height: 1600,
    alt: "notes",
  },
  cyan: {
    url: "./assets/cyan.png",
    webP: "./assets/cyan.webp",
    width: 2336,
    height: 1600,
    alt: "cyan",
  },
  orbs: {
    url: "./assets/orbs.png",
    webP: "./assets/orbs.webp",
    width: 2340,
    height: 1200,
    alt: "orbs",
  },
  multiMesh1: {
    url: "./assets/multiMesh1.png",
    webP: "./assets/multiMesh1.webp",
    width: 1174,
    height: 1182,
    alt: "multiMesh1",
  },
  multiMesh0: {
    url: "./assets/multiMesh0.png",
    webP: "./assets/multiMesh0.webp",
    width: 582,
    height: 582,
    alt: "multiMesh0",
  },
  logoStrip: {
    url: "./assets/logoStrip.svg",
    width: 102,
    height: 588,
    alt: "logoStrip",
  },
  twentytwenty: {
    url: "./assets/2020.svg",
    width: 81,

    height: 23,
    alt: "twentytwenty",
  },
  styrenebold: {
    url: "./assets/styrenebold.svg",
    width: 311,
    height: 123,
    alt: "styrenebold",
  },
  raisonne: {
    url: "./assets/raisonne.svg",
    width: 204,
    height: 128,
    alt: "raisonne",
  },
  styrene: {
    url: "./assets/styrene.svg",
    width: 217,
    height: 94,
    alt: "styrene",
  },
  monomeshMagenta1: {
    url: "./assets/monomeshMagenta1.png",
    webP: "./assets/monomeshMagenta1.webp",
    width: 1280,
    height: 1280,
    alt: "monomeshMagenta1",
  },
  monomeshMagenta: {
    url: "./assets/monomeshMagenta.png",
    webP: "./assets/monomeshMagenta.webp",
    width: 1280,
    height: 1280,
    alt: "monomeshMagenta",
  },
  monomeshRed2: {
    url: "./assets/monomeshRed2.png",
    webP: "./assets/monomeshRed2.webp",
    width: 1280,
    height: 1280,
    alt: "monomeshRed2",
  },
  monomeshOrange: {
    url: "./assets/monomeshOrange.png",
    webP: "./assets/monomeshOrange.webp",
    width: 1280,
    height: 1280,
    alt: "monomeshOrange",
  },
  monomeshRed: {
    url: "./assets/monomeshRed.png",
    webP: "./assets/monomeshRed.webp",
    width: 1280,
    height: 1280,
    alt: "monomeshRed",
  },
  monomeshCyan1: {
    url: "./assets/monomeshCyan1.png",
    webP: "./assets/monomeshCyan1.webp",
    width: 1280,
    height: 1280,
    alt: "monomeshcyan1",
  },
  pageHomeMobile: {
    url: "./assets/pageHomeMobile.jpg",
    webP: "./assets/pageHomeMobile.webp",
    width: 750,
    height: 2666,
    alt: "pageHomeMobile",
  },
  pageTickets: {
    url: "./assets/pageTickets.jpg",
    webP: "./assets/pageTickets.webp",
    width: 2336,
    height: 3204,
    alt: "pageTickets",
  },
  pageTicketsMobile: {
    url: "./assets/pageTicketsMobile.jpg",
    webP: "./assets/pageTicketsMobile.webp",
    width: 750,
    height: 4097,
    alt: "pageTicketsMobile",
  },
  pageInformation1: {
    url: "./assets/pageInformation1.jpg",
    webP: "./assets/pageInformation1.webp",
    width: 2336,
    height: 2860,
    alt: "pageInformation1",
  },
  pageInformation2: {
    url: "./assets/pageInformation2.jpg",
    webP: "./assets/pageInformation2.webp",
    width: 2336,
    height: 2558,
    alt: "pageInformation2",
  },
  pageInformation3: {
    url: "./assets/pageInformation3.jpg",
    webP: "./assets/pageInformation3.webp",
    width: 2336,
    height: 1936,
    alt: "pageInformation3",
  },
  pageWorkshops1: {
    url: "./assets/pageWorkshops1.jpg",
    webP: "./assets/pageWorkshops1.webp",
    width: 2336,
    height: 2559,
    alt: "pageWorkshops1",
  },
  pageWorkshops2: {
    url: "./assets/pageWorkshops2.jpg",
    webP: "./assets/pageWorkshops2.webp",
    width: 2336,
    height: 2608,
    alt: "pageWorkshops2",
  },
  pageSpeakers: {
    url: "./assets/pageSpeakers.jpg",
    webP: "./assets/pageSpeakers.webp",
    width: 2336,
    height: 2591,
    alt: "pageSpeakers",
  },
  pageFaq: {
    url: "./assets/pageFaq.jpg",
    webP: "./assets/pageFaq.webp",
    width: 2336,
    height: 2339,
    alt: "pageFaq",
  },
  pageHome: {
    url: "./assets/pageHome.jpg",
    webP: "./assets/pageHome.webp",
    width: 2336,
    height: 2416,
    alt: "pageHome",
  },
  webdesign: {
    url: "./assets/webdesign.png",
    webP: "./assets/webdesign.webp",
    width: 3020,
    height: 4492,
    alt: "Web Design",
  },
  execution: {
    url: "./assets/execution.png",
    webP: "./assets/execution.webp",
    width: 3020,
    height: 9498,
    alt: "Web Design",
  },
  exe1: {
    url: "./assets/exe1.png",
    webP: "./assets/exe1.webp",
    width: 2265,
    height: 2393,
    alt: "Execution",
  },
  exe2: {
    url: "./assets/exe2.png",
    webP: "./assets/exe2.webp",
    width: 2265,
    height: 1929,
    alt: "Execution",
  },
  exe3: {
    url: "./assets/exe3.png",
    webP: "./assets/exe3.webp",
    width: 2265,
    height: 2000,
    alt: "Execution",
  },
  exe4: {
    url: "./assets/exe4.png",
    webP: "./assets/exe4.webp",
    width: 2265,
    height: 1954,
    alt: "Execution",
  },
};
