export const colors = {
  red: "#f60000",
  cyan: "#3edbff",
  orange: "#f47722",
  green: "#003807",
  beige: "#fcf6f5",
  magenta: "#e900a1",
  maroon: "#560000",
  white: "#fff",
};

export const videos = {
  loupeMesh: {
    url: "loupeMesh.mp4",
    width: 1080,
    height: 1080,
  },
  mesh: {
    url: "mesh.mp4",
    width: 1080,
    height: 1080,
  },
  mesh1: {
    url: "mesh1.mp4",
    width: 1152,
    height: 1152,
  },
  muziekclip: {
    fit: "cover",
    url: "muziekclip.mp4",
    width: 2646,
    height: 1080,
  },
  icons: {
    url: "icons.mp4",
    width: 1080,
    height: 1080,
    fit: "cover",
  },
  overview: {
    url: "overview.mp4",
    width: 1168,
    height: 620,
  },
};

export const images = {
  logopart1: {
    name: "logopart1.png",
    width: 1,
    height: 1,
    alt: "logopart1",
  },
  logopart2: {
    name: "logopart2.png",
    width: 1,
    height: 1,
    alt: "logopart2",
  },
  logopart3: {
    name: "logopart3.png",
    width: 1,
    height: 1,
    alt: "logopart3",
  },
  logopart4: {
    name: "logopart4.png",
    width: 1,
    height: 1,
    alt: "logopart4",
  },
  logoassemble1: {
    name: "logoassemble1.png",
    width: 1,
    height: 1,
    alt: "logoassemble1",
  },
  logoassemble2: {
    name: "logoassemble2.png",
    width: 1,
    height: 1,
    alt: "logoassemble2",
  },
  logoassemble3: {
    name: "logoassemble3.png",
    width: 1,
    height: 1,
    alt: "logoassemble3",
  },
  shapesFilled: {
    name: "shapesFilled.png",
    webP: "shapesFilled.webp",
    width: 2340,
    height: 1818,
    alt: "logowithmesh",
  },
  logowithmesh: {
    name: "logowithmesh.png",
    webP: "logowithmesh.webp",
    width: 2340,
    height: 1200,
    alt: "logowithmesh",
  },
  meshwithnotes: {
    name: "meshwithnotes.png",
    webP: "meshwithnotes.webp",
    width: 2340,
    height: 1200,
    alt: "meshwithnotes",
  },
  overview: {
    name: "overview.jpg",
    webP: "overview.webp",
    width: 4000,
    height: 2928,
    alt: "overview",
  },
  notes: {
    name: "notes.png",
    webP: "notes.webp",
    width: 2340,
    height: 1600,
    alt: "notes",
  },
  cyan: {
    name: "cyan.png",
    webP: "cyan.webp",
    width: 2336,
    height: 1600,
    alt: "cyan",
  },
  orbs: {
    name: "orbs.png",
    webP: "orbs.webp",
    width: 2340,
    height: 1200,
    alt: "orbs",
  },
  multiMesh1: {
    name: "multiMesh1.png",
    webP: "multiMesh1.webp",
    width: 1174,
    height: 1182,
    alt: "multiMesh1",
  },
  multiMesh0: {
    name: "multiMesh0.png",
    webP: "multiMesh0.webp",
    width: 582,
    height: 582,
    alt: "multiMesh0",
  },
  logoStrip: {
    name: "logoStrip.svg",
    width: 102,
    height: 588,
    alt: "logoStrip",
  },
  twentytwenty: {
    name: "2020.svg",
    width: 81,

    height: 23,
    alt: "twentytwenty",
  },
  styrenebold: {
    name: "styrenebold.svg",
    width: 311,
    height: 123,
    alt: "styrenebold",
  },
  raisonne: {
    name: "raisonne.svg",
    width: 204,
    height: 128,
    alt: "raisonne",
  },
  styrene: {
    name: "styrene.svg",
    width: 217,
    height: 94,
    alt: "styrene",
  },
  monomeshMagenta1: {
    name: "monomeshMagenta1.png",
    webP: "monomeshMagenta1.webp",
    width: 1280,
    height: 1280,
    alt: "monomeshMagenta1",
  },
  monomeshMagenta: {
    name: "monomeshMagenta.png",
    webP: "monomeshMagenta.webp",
    width: 1280,
    height: 1280,
    alt: "monomeshMagenta",
  },
  monomeshRed2: {
    name: "monomeshRed2.png",
    webP: "monomeshRed2.webp",
    width: 1280,
    height: 1280,
    alt: "monomeshRed2",
  },
  monomeshOrange: {
    name: "monomeshOrange.png",
    webP: "monomeshOrange.webp",
    width: 1280,
    height: 1280,
    alt: "monomeshOrange",
  },
  monomeshRed: {
    name: "monomeshRed.png",
    webP: "monomeshRed.webp",
    width: 1280,
    height: 1280,
    alt: "monomeshRed",
  },
  monomeshCyan1: {
    name: "monomeshCyan1.png",
    webP: "monomeshCyan1.webp",
    width: 1280,
    height: 1280,
    alt: "monomeshcyan1",
  },
  pageHomeMobile: {
    name: "pageHomeMobile.jpg",
    webP: "pageHomeMobile.webp",
    width: 750,
    height: 2666,
    alt: "pageHomeMobile",
  },
  pageTickets: {
    name: "pageTickets.jpg",
    webP: "pageTickets.webp",
    width: 2336,
    height: 3204,
    alt: "pageTickets",
  },
  pageTicketsMobile: {
    name: "pageTicketsMobile.jpg",
    webP: "pageTicketsMobile.webp",
    width: 750,
    height: 4097,
    alt: "pageTicketsMobile",
  },
  pageInformation1: {
    name: "pageInformation1.jpg",
    webP: "pageInformation1.webp",
    width: 2336,
    height: 2860,
    alt: "pageInformation1",
  },
  pageInformation2: {
    name: "pageInformation2.jpg",
    webP: "pageInformation2.webp",
    width: 2336,
    height: 2558,
    alt: "pageInformation2",
  },
  pageInformation3: {
    name: "pageInformation3.jpg",
    webP: "pageInformation3.webp",
    width: 2336,
    height: 1936,
    alt: "pageInformation3",
  },
  pageWorkshops1: {
    name: "pageWorkshops1.jpg",
    webP: "pageWorkshops1.webp",
    width: 2336,
    height: 2559,
    alt: "pageWorkshops1",
  },
  pageWorkshops2: {
    name: "pageWorkshops2.jpg",
    webP: "pageWorkshops2.webp",
    width: 2336,
    height: 2608,
    alt: "pageWorkshops2",
  },
  pageSpeakers: {
    name: "pageSpeakers.jpg",
    webP: "pageSpeakers.webp",
    width: 2336,
    height: 2591,
    alt: "pageSpeakers",
  },
  pageFaq: {
    name: "pageFaq.jpg",
    webP: "pageFaq.webp",
    width: 2336,
    height: 2339,
    alt: "pageFaq",
  },
  pageHome: {
    name: "pageHome.jpg",
    webP: "pageHome.webp",
    width: 2336,
    height: 2416,
    alt: "pageHome",
  },
  webdesign: {
    name: "webdesign.png",
    webP: "webdesign.webp",
    width: 3020,
    height: 4492,
    alt: "Web Design",
  },
  execution: {
    name: "execution.png",
    webP: "execution.webp",
    width: 3020,
    height: 9498,
    alt: "Web Design",
  },
  exe1: {
    name: "exe1.png",
    webP: "exe1.webp",
    width: 2265,
    height: 2393,
    alt: "Execution",
  },
  exe2: {
    name: "exe2.png",
    webP: "exe2.webp",
    width: 2265,
    height: 1929,
    alt: "Execution",
  },
  exe3: {
    name: "exe3.png",
    webP: "exe3.webp",
    width: 2265,
    height: 2000,
    alt: "Execution",
  },
  exe4: {
    name: "exe4.png",
    webP: "exe4.webp",
    width: 2265,
    height: 1954,
    alt: "Execution",
  },
};
