export const images = {
  web0: {
    name: "web-0.png",
    width: 1200,
    height: 720,
    alt: "AI notes",
  },
  web1: {
    name: "web-1.png",
    width: 1200,
    height: 720,
    alt: "Value Proposition",
  },
  web2: {
    name: "web-2.png",
    width: 1200,
    height: 720,
    alt: "Landing pages",
  },
  web3: {
    name: "web-3.png",
    width: 1200,
    height: 720,
    alt: "Custom mobile designs",
  },
  web4: {
    name: "web-4.png",
    width: 1200,
    height: 720,
    alt: "AI notes parallax",
  },
  bb0: {
    name: "bb-0.png",
    width: 1200,
    height: 675,
    alt: "Colors",
  },
  bb1: {
    name: "bb-1.png",
    width: 1200,
    height: 675,
    alt: "Social asset",
  },
  bb2: {
    name: "bb-2.png",
    width: 1200,
    height: 675,
    alt: "Mascot",
  },
  bb3: {
    name: "bb-3.png",
    width: 1200,
    height: 675,
    alt: "Ribbon style",
  },
  bb4: {
    name: "bb-4.png",
    width: 1200,
    height: 675,
    alt: "Setup",
  },
  bb5: {
    name: "bb-5.png",
    width: 1200,
    height: 675,
    alt: "Blog asset",
  },
  heroMobile: {
    name: "hero-mobile.png",
    width: 576,
    height: 437,
    alt: "Hero Mobile",
  },
  heroCTA: {
    name: "hero-cta.png",
    width: 432,
    height: 229,
    alt: "Hero CTA",
  },
  heroBubble: {
    name: "hero-bubble.png",
    width: 368,
    height: 229,
    alt: "Hero Bubble",
  },
  heroChart: {
    name: "hero-chart.png",
    width: 610,
    height: 384,
    alt: "Hero Chart",
  },
  heroCard: {
    name: "hero-card.png",
    width: 568,
    height: 320,
    alt: "Hero Card",
  },
  heroGreenRibbon: {
    name: "hero-green-ribbon.png",
    width: 308,
    height: 501,
    alt: "Hero Green Ribbon",
  },
  heroIcons: {
    name: "hero-icons.png",
    width: 170,
    height: 448,
    alt: "Hero Icons",
  },
  heroSpag: {
    name: "hero-spag.png",
    width: 288,
    height: 281,
    alt: "Hero Spag",
  },
};
